### ISSUE TITLE
请问代码中是如何结合prompt？

### ISSUE THREAD

**Issue by pony-m** [zjunlp/PromptKG#11]
感谢作者们的回复~
项目中提供了4种模型，用于补全和问答两项任务，输入、输出均是三元组。但不太清楚怎样结合了prompt，望解答~

**Comment by CheaSim** [comment]
我们的模型中，有部分主要是利用实体和关系的文本信息来增强语言模型连接预测的推理能力。
比较具体的是，在`GenKGC`中，我们会从训练数据中采样相同的三元组来增加模型对链接预测的理解。
在`kNNKGE`中，就是和prompt形式一样，将链接预测任务转化为了MLM任务，在输入中也含有文本的提示prompt来增强模型推理。

**Comment by zxlzr** [comment]
您好，我们的工具旨在提供一个统一的基于prompt的知识图谱任务框架，具体prompt形式会在近期挂出的论文中详细表达。
