### ISSUE TITLE
loss没有下降

### ISSUE THREAD

**Issue by zhu1090093659** [zjunlp/PromptKG#13]
按照教程执行操作，程序运行起来后loss一直是2.98，请问这是什么问题？
执行的任务是semeval，除了batch_size其他的都没有改变

**Comment by zxlzr** [comment]
您好我们近期在赶ddl，近期会尽快检查代码协助解决您提出的问题，

**Comment by CheaSim** [comment]
你好，可以尝试更换`pytorch_lightning`版本，更新到最新版，或者是回退到`1.3.1`.

**Comment by yiyi1333** [comment]
> 按照教程执行操作，程序运行起来后loss一直是2.98，请问这是什么问题？ 执行的任务是semeval，除了batch_size其他的都没有改变

请问你解决loss不降低的问题了吗

**Comment by yiyi1333** [comment]
> > 按照教程执行操作，程序运行起来后loss一直是2.98，请问这是什么问题？ 执行的任务是semeval，除了batch_size其他的都没有改变
> 
> 请问你解决loss不降低的问题了吗

我也解决了训练过程中loss不降低的问题，需要将pytorch-lightning的版本使用1.3.1，对应的torchmetric的版本为0.5.0即可

**Comment by zxlzr** [comment]
请问这个问题的issue解决了吗，如已解决烦请关闭issue

**Comment by yiyi1333** [comment]
是的，我已经解决了该问题
