### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by YangLing0818** [zjunlp/PromptKG#14]
I comes up with a running error of:
File "data/processor.py", line 417, in _create_examples
    relation_names.append(rel2text[t])                                                                             
KeyError: '/soccer/football_team/current_roster./soccer/football_roster_position/position'
when I run the command "sh ./scripts/wn18rr.sh" in project GenKGC

**Comment by CheaSim** [comment]
Make sure you download the same format of our preprocessed dataset in `GenKGC` ， you can download the dataset via this link https://drive.google.com/drive/folders/1lo7GEkOzonoaJJ9edHTwMYEl6BajmLQg?usp=sharing
