### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by YangLing0818** [zjunlp/PromptKG#15]
It seems that file WN18RR/relations.txt is not uploaded

**Comment by CheaSim** [comment]
We recommend you run the `GenKGC` script in our toolkit which under https://github.com/zjunlp/PromptKG/blob/main/toolkit/scripts/kgc/genkgc.sh , we will maintain and update all the features in the model in that code base. And all the dataset formats is 
* entity2text.txt 
* relation2text.txt 
* train.tsv dev.tsv test.tsv.
