### ISSUE TITLE
run

### ISSUE THREAD

**Issue by yinjiexidian** [zjunlp/PromptKG#19]
你好我在运行的时候遇到一个问题：Repository not found for URL: https://huggingface.co/pretrained_model/resolve/main/config.json.
GenKGC用的是哪一个Bert预训练模型呀？

**Comment by CheaSim** [comment]
你好，GenKGC使用的预训练语言模型权重是`facebook/bart-base`, 你可以修改参数`model_name_or_path`来指定预训练语言模型权重。

**Comment by yinjiexidian** [comment]
感谢你的回答，我试一试
