### ISSUE TITLE
没有requirements.txt  文件

### ISSUE THREAD

**Issue by pony-m** [zjunlp/PromptKG#2]
可以尽快更新一下 requirements.txt 文件嘛

**Comment by zxlzr** [comment]
请问您指的是哪个子项目

**Comment by pony-m** [comment]
[PromptKGC

**Comment by pony-m** [comment]
PromptKGC
github上也给您回复了一下



| |
马正
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月08日 19:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zjunlp/PromptKG] 没有requirements.txt  文件 (Issue #2) |

请问您指的是哪个子项目

**Comment by CheaSim** [comment]
Sorry, we miss the `requirements.txt` file in the `PromptKGC`. You can git clone the latest repo to get the added file.

**Comment by pony-m** [comment]
> Sorry, we miss the `requirements.txt` file in the `PromptKGC`. You can git clone the latest repo to get the added file.

运行 pip install -r requirements.txt：

ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cu111
ERROR: Could not find a version that satisfies the requirement transformers==3.3.4 
ERROR: Could not find a version that satisfies the requirement dataclasses==0.8
