### ISSUE TITLE
请教一下关于将实体/关系视作special_token的问题。

### ISSUE THREAD

**Issue by estuday** [zjunlp/PromptKG#20]
您好，感谢分享工作成果。

在您的论文里指出将实体/关系视作special_token，我看了公布的代码后发现，tokenizer只添加100个类似`[ENTITY_{j}{i}]`的特殊字符，这一块似乎还没做完对吗？ 

不知道能否讲一下关于这一块的细节？

**Comment by CheaSim** [comment]
感谢你对我们工作的关注。
`[ENTITY_{j}{i}]` 涉及到我们现在还在开发的将实体视作序列的方案。
目前，我们项目中将实体视作special_token，在这里因为huggingface中Tokenizer如果加入了过多的较为类似的special token, 比如有5w个实体，加入5w个special_token 会导致tokenize的速度很慢，所以我们在tokenize的过程中，将实体先用占位符替代，再替换成实体对应的special token id 输入到模型中。
这部分的代码可以看
https://github.com/zjunlp/PromptKG/blob/114960624a7cd5a8a79c42270afbc4c826713327/toolkit/data/data_module.py#L384-L411
我们`KNNKGE`中的`collate_fn`形式。

**Comment by estuday** [comment]
感谢您的解答。

事实上，受到您论文里的启发。我在尝试把Seq2Seq用在KGC上时，想借鉴您提到的encode方法。因此我想搞懂，在实体视作序列方案中，将实体视为special token的具体思路。

在论文中，我以为您将实体视为special token是prompt的一种方式，即输入进模型里的实体也视为special token。可现在看来，您提出的这个方案就是为了加快tokenize的速度。而论文里的prompt实质上还是指加上了实体描述。我这样的理解对吗？

**Comment by CheaSim** [comment]
1. 实体作为token序列还在实验中，如果有最新进展会在这个repo中更新，请持续关注~
2. Prompt本质还是在于实体描述信息作为模型的 **提示**, 同时我们也会在输入中加入训练集中的三元组来辅助推理，这就是我们设定的`Prompt`。
