### ISSUE TITLE
'dataset/FB15k-237/entity2textlong.txt' not found

### ISSUE THREAD

**Issue by detectiveJoshua** [zjunlp/PromptKG#25]
It seems that there is not a file named entity2textlong.txt in dataset FB15k-237. But you load this file in /LLM/create_midres.py. 
Could you tell me where this file comes from? Or did I miss something?

**Comment by CheaSim** [comment]
Sorry for the missed file, we have uploaded to the google drive, you can download it from this link https://drive.google.com/drive/folders/1aNkuAIQeFOfN4B04xnBOzxhMZKNMxoBH?usp=sharing

**Comment by detectiveJoshua** [comment]
It works after trying your method. But another problem occurred when excuting LLM\atomic2020_process.py. It seems that: 
`rel = line.strip().strip().split("@@")[1].strip()` should be
`rel = line.strip().split("\t")[0].split("@@")[1].strip()` on line 25.
Otherwise, it would not run successfully.

**Comment by zxlzr** [comment]
Sorry, we will fix it soon.

**Comment by zxlzr** [comment]
It has been fixed.
