### ISSUE TITLE
create MidRes.json isn't working

### ISSUE THREAD

**Issue by Lim-YoungYoon** [zjunlp/PromptKG#26]
When I download FB15K-237 using Google Drive and run MidRes.json file, I get the following error. Please check..
I looked up the problem, but there is no difference between the entity2text.txt file uploaded to Google Drive and the entity2textlong.txt file.

 run python ./LLM/create_midres.py

'''
Traceback (most recent call last):
  File "./LLM/create_midres.py", line 39, in <module>
    build_midres()
  File "./LLM/create_midres.py", line 28, in build_midres
    for i in entity2textlong[lines[0]].replace('\\n',' ').split('. '):
KeyError: '9447'
'''

**Comment by zxlzr** [comment]
Hi, sorry, the preprocessing code is missing and we will update these code ASAP.

**Comment by zxlzr** [comment]
Hi, the bug has been fixed and please try it again.

**Comment by Lim-YoungYoon** [comment]
> Hi, the bug has been fixed and please try it again.

''''
def run(args):
   candidate_num=args.candidate_num
''''
Code must be indente

and

'''
def test_on_gpt3(prompt,answer,count):
try:
promts = BasePrompt()
promts.build_prompt(prompt)
response = promts.get_openai_result(engine = "text-davinci-003", temperature = 0.5, max_tokens = 200)
time.sleep(1.5)
except:
print("An error occurred while calling the OpenAI API for text-davinci-003!")

if answer in response['choices'][0]['text']:
    count+=1
    
return count
'''
/root/anaconda3/envs/KG/lib/python3.8/site-packages/requests/init.py:109: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (None)/charset_normalizer (3.1.0) doesn't match a supported version!
warnings.warn(
An error occurred while calling the OpenAI API for text-davinci-003!
Traceback (most recent call last):
File "./LLM/gpt3kgc.py", line 159, in
run(args)
File "./LLM/gpt3kgc.py", line 122, in run
count=test_on_gpt3(prompt,entity2text[items[2]],count)
File "./LLM/gpt3kgc.py", line 150, in test_on_gpt3
if answer in response['choices'][0]['text']:
UnboundLocalError: local variable 'response' referenced before assignment

Maybe the way to call openai api is wrong. Please review it.

**Comment by Wangxh-07** [comment]
Thank you for your careful inspection and suggestions. The indentation has been modified now.
And please check your openai_key or the proxy if you use it in File "./LLM/gpt3kgc.py", line 15.
