### ISSUE TITLE
bash ./scripts/metaqa/run.sh  运行中遇到的问题

### ISSUE THREAD

**Issue by vandarkfan** [zjunlp/PromptKG#27]
PromptKG-main/lambdaKG/lit_models/transformer.py中
batch_data = batch.pop("batch_data")
找不到属性，batch中没有batch_data，请问如何处理呢

**Comment by CheaSim** [comment]
你好，我们已经在代码中进行纠正，可以加入一个判断语句，
```python
if "batch_data" in batch:
    batch_data = batch.pop("batch_data")
```

**Comment by vandarkfan** [comment]
这个方法我试过，就是把batch_data给取消掉了，但是取消掉之后，计算rank归零了，我猜想是不是这个batch_data里面的hr和t是计算rank必须的呢，是否需要在collate_fn部分加上batch_data呢

**Comment by CheaSim** [comment]
KGT5使用label标签硬匹配得到结果，不需要batch_data,KBQA的训练需要更长的时间，你可以调整一下验证的epoch，设置为
```shell
   --check_val_every_n_epoch 5 
```
可以较快得到结果。
