### ISSUE TITLE
cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/home/mz20/.local/lib/python3.8/site-packages/torchmetrics/utilities/data.py)

### ISSUE THREAD

**Issue by pony-m** [zjunlp/PromptKG#3]
Error occurs when running main.py :
cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/home/mz20/.local/lib/python3.8/site-packages/torchmetrics/utilities/data.py)

**Comment by CheaSim** [comment]
Change the transformers version to `4.3.0`.
