### ISSUE TITLE
GenKGC中提供的数据集链接google derive需要权限

### ISSUE THREAD

**Issue by WEIYanbin1999** [zjunlp/PromptKG#30]
您好，我想要下载GenKGC中提供的数据集链接

https://drive.google.com/drive/folders/1carN96-mvbYfW_X1Rt-eLCGjEYx3iOda?usp=sharing
![image](https://github.com/zjunlp/PromptKG/assets/127707751/d176b8fe-a49e-4613-8742-c1626c9fcee5)

google derive需要权限 提示没有权限访问 请问这是正常的吗

**Comment by CheaSim** [comment]
现在链接已更新，可以正常访问下载了。

**Comment by WEIYanbin1999** [comment]
谢谢~
