### ISSUE TITLE
fb15k-237 dataset 

### ISSUE THREAD

**Issue by star-rui** [zjunlp/PromptKG#31]
fb15k-237 dataset 需要自己手动下载放到项目目录中吗

**Comment by CheaSim** [comment]
嗯，所有数据集合需要手动下载放到`dataset`目录下。

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by star-rui** [comment]
https://github.com/zjunlp/PromptKG/tree/main/research/PromptKGC/dataset  已经在这个链接中找到fb15k-237数据集

**Comment by star-rui** [comment]
https://github.com/zjunlp/PromptKG/tree/main/research/PromptKGC/dataset
已在这个链接中找到GenKGC项目需要的fb15k-237数据集




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/PromptKG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月11日(星期天) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/PromptKG] fb15k-237 dataset  (Issue #31)





 
请问您的问题解决了吗

**Comment by zxlzr** [comment]
好的
