### ISSUE TITLE
GenKGC下的pytorch_lightning==1.3.1

### ISSUE THREAD

**Issue by RongchuanTang** [zjunlp/PromptKG#32]
请问pytorch_lightning==1.3.1是用什么命令怎么安装的呀，安装一直报错。

**Comment by RongchuanTang** [comment]
使用pip安装成功了~
参考了博客https://blog.csdn.net/qq_60592939/article/details/129177520

**Comment by zxlzr** [comment]
抱歉给您带来了不便，我们未来会完善一下安装说明。

**Comment by RongchuanTang** [comment]
我运行成功了，训练没有遇到问题~

**Comment by zxlzr** [comment]
好滴
