### ISSUE TITLE
请问GenKGC的代码您运行成功了吗

### ISSUE THREAD

**Issue by star-rui** [zjunlp/PromptKG#33]
使用pip安装成功了~
参考了博客https://blog.csdn.net/qq_60592939/article/details/129177520

_Originally posted by @RongchuanTang in https://github.com/zjunlp/PromptKG/issues/32#issuecomment-1586758560_

**Comment by RongchuanTang** [comment]
我运行成功了，训练没有遇到问题~

**Comment by star-rui** [comment]
非常抱歉又打扰您了，请问您是根据requirements.txt利用pip安装完对应包，下载好数据集，就直接可以运行脚本文件了吗，还有其它操作吗？有对脚本文件或者代码进行修改吗？非常期待并且感谢您的回复，这对我非常重要。再次表示感谢！

**Comment by RongchuanTang** [comment]
> 非常抱歉又打扰您了，请问您是根据requirements.txt利用pip安装完对应包，下载好数据集，就直接可以运行脚本文件了吗，还有其它操作吗？有对脚本文件或者代码进行修改吗？非常期待并且感谢您的回复，这对我非常重要。再次表示感谢！

没有修改欸，只把脚本里的gpus数量设为了1，要不你把你各个安装包的版本放上来看看

**Comment by star-rui** [comment]
非常感谢
(genkgc) root@dl-2306060117525lg-pod-jupyter-6c8cb7979c-5ljfw:~/PromptKG/research/GenKGC# pip list
Package                  Version
------------------------ ------------
absl-py                  1.4.0
activations              0.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
appdirs                  1.4.4
asttokens                2.2.1
async-timeout            4.0.2
attrs                    23.1.0
backcall                 0.2.0
cachetools               5.3.1
certifi                  2023.5.7
cffi                     1.15.1
charset-normalizer       3.1.0
chex                     0.1.7
click                    8.1.3
cmake                    3.26.3
contourpy                1.0.7
cryptography             41.0.1
cycler                   0.11.0
dataclasses              0.6
decorator                5.1.1
dm-tree                  0.1.8
docker-pycreds           0.4.0
executing                1.2.0
file.utils               0.0.1
filelock                 3.12.0
flax                     0.3.4
fonttools                4.39.4
frozenlist               1.3.3
fsspec                   2023.5.0
future                   0.18.3
gitdb                    4.0.10
GitPython                3.1.31
google-auth              2.19.1
google-auth-oauthlib     1.0.0
grpcio                   1.54.2
huggingface-hub          0.0.8
idna                     3.4
importlib-metadata       6.6.0
importlib-resources      5.12.0
ipython                  8.12.2
jax                      0.4.11
jaxlib                   0.4.11
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
kiwisolver               1.4.4
lit                      16.0.5.post0
Markdown                 3.4.3
MarkupSafe               2.1.3
matplotlib               3.7.1
matplotlib-inline        0.1.6
ml-dtypes                0.1.0
mpmath                   1.3.0
msgpack                  1.0.5
multidict                6.0.4
networkx                 3.1
numpy                    1.20.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
opt-einsum               3.3.0
optax                    0.1.5
packaging                23.1
parso                    0.8.3
pathtools                0.1.2
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.0.1
prompt-toolkit           3.0.38
protobuf                 4.23.2
psutil                   5.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pycparser                2.21
pyDeprecate              0.3.0
Pygments                 2.15.1
pyOpenSSL                23.2.0
pyparsing                3.0.9
python-dateutil          2.8.2
pytorch-lightning        1.3.1
PyYAML                   5.4.1
regex                    2021.4.4
requests                 2.31.0
requests-oauthlib        1.3.1
rsa                      4.9
sacremoses               0.0.53
scipy                    1.10.1
sentry-sdk               1.25.1
setproctitle             1.3.2
setuptools               67.8.0
six                      1.16.0
smmap                    5.0.0
stack-data               0.6.2
sympy                    1.12
tensorboard              2.13.0
tensorboard-data-server  0.7.0
tokenizers               0.10.3
toolz                    0.12.0
torch                    1.8.1
torchaudio               0.8.1
torchmetrics             0.5.0
torchvision              0.9.1
tqdm                     4.49.0
traitlets                5.9.0
transformers             4.7.0
triton                   2.0.0
typing_extensions        4.6.2
urllib3                  1.26.16
utils                    1.0.1
wandb                    0.15.4
wcwidth                  0.2.6
Werkzeug                 2.3.4
wheel                    0.38.4
yarl                     1.9.2
zipp                     3.15.0

**Comment by star-rui** [comment]
> > 非常抱歉又打扰您了，请问您是根据requirements.txt利用pip安装完对应包，下载好数据集，就直接可以运行脚本文件了吗，还有其它操作吗？有对脚本文件或者代码进行修改吗？非常期待并且感谢您的回复，这对我非常重要。再次表示感谢！
> 
> 没有修改欸，只把脚本里的gpus数量设为了1，要不你把你各个安装包的版本放上来看看

如果方便的话可以麻烦您把您虚拟环境中安装的包粘贴一下吗，我想对照一下我安装的包是不是哪里有问题。非常感谢，谢谢您！

**Comment by RongchuanTang** [comment]
Package                  Version
------------------------ ------------
absl-py                  1.4.0
aiohttp                  3.8.4
aiosignal                1.3.1
appdirs                  1.4.4
asttokens                2.2.1
async-timeout            4.0.2
attrs                    23.1.0
backcall                 0.2.0
cachetools               5.3.1
certifi                  2023.5.7
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.4
decorator                5.1.1
docker-pycreds           0.4.0
executing                1.2.0
filelock                 3.12.1
frozenlist               1.3.3
fsspec                   2023.6.0
future                   0.18.3
gitdb                    4.0.10
GitPython                3.1.31
google-auth              2.19.1
google-auth-oauthlib     1.0.0
grpcio                   1.54.2
huggingface-hub          0.0.8
idna                     3.4
importlib-metadata       6.6.0
ipython                  8.12.2
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
lit                      16.0.5.post0
Markdown                 3.4.3
MarkupSafe               2.1.3
matplotlib-inline        0.1.6
mpmath                   1.3.0
multidict                6.0.4
networkx                 3.1
numpy                    1.24.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
packaging                23.1
parso                    0.8.3
pathtools                0.1.2
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.0.1
prompt-toolkit           3.0.38
protobuf                 4.23.2
psutil                   5.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pyDeprecate              0.3.0
Pygments                 2.15.1
pytorch-lightning        1.3.1
PyYAML                   5.4.1
regex                    2021.4.4
requests                 2.31.0
requests-oauthlib        1.3.1
rsa                      4.9
sacremoses               0.0.53
sentry-sdk               1.25.1
setproctitle             1.3.2
setuptools               67.8.0
six                      1.16.0
smmap                    5.0.0
stack-data               0.6.2
sympy                    1.12
tensorboard              2.13.0
tensorboard-data-server  0.7.0
tokenizers               0.10.3
torch                    1.7.1+cu110
torchaudio               0.7.2
torchmetrics             0.5.0
torchvision              0.8.2+cu110
tqdm                     4.65.0
traitlets                5.9.0
transformers             4.7.0
triton                   2.0.0
typing_extensions        4.6.3
urllib3                  1.26.16
wandb                    0.15.4
wcwidth                  0.2.6
Werkzeug                 2.3.6
wheel                    0.38.4
yarl                     1.9.2
zipp                     3.15.0
你对比看看

**Comment by star-rui** [comment]
非常不好意思想再问一下，您用GPU训练的时候，用的多大的内存，有没有报内存不够的错误，我用显卡预训练的，显卡大小是8000MiB,报错RuntimeError: CUDA out of memory.，感谢！

**Comment by RongchuanTang** [comment]
我是12G的卡，你可以把模型改为bart-base或者调小batch_size试一下

**Comment by star-rui** [comment]
真的非常感谢您！多亏了您的帮助，我才能成功地运行代码。
