### ISSUE TITLE
运行bash ./scripts/kgc/knnkge.sh时报错AttributeError: 'KNNKGEPretrainLitModel' object has no attribute 'model'

### ISSUE THREAD

**Issue by Roger-Ni** [zjunlp/PromptKG#46]
![截图 2023-11-09 16-51-12](https://github.com/zjunlp/PromptKG/assets/71998483/a45a46de-c63a-48cd-8b4b-95d23de3bf9c)
我想训练knn-kg模型，出现如上图所示错误。

**Comment by CheaSim** [comment]
请问一下transformers和pytorch_lightning的版本，以及模型文件是否成功下载。

**Comment by Roger-Ni** [comment]
transformers==4.15.0  pytorch_lighting==1.6.0 .模型文件的话，我看knnkge.sh文件中写的是model_name_or_path="bert-base-uncased"，就认为应该是下载bert的模型，我就下载到了如下图所示的目录下。
![截图 2023-11-10 14-41-01](https://github.com/zjunlp/PromptKG/assets/71998483/e08332fa-a930-4f66-baaa-bf4d29e873a9)
然后bert-base-uncased文件夹下的文件应该也是齐全的（如下图所示）
![截图 2023-11-10 14-42-12](https://github.com/zjunlp/PromptKG/assets/71998483/236943fa-dbfe-41a1-9d18-8db515de8219)

**Comment by CheaSim** [comment]
请把transformers 版本和requirements.txt 保持一致。
```shelll
transformers==4.6.0
```

**Comment by zxlzr** [comment]
请问您的问题是否已解决

**Comment by Roger-Ni** [comment]
我把transformers和pytorch_lighting都配置成了rquirements中的版本，但是运行时，还是会出现如下错误。
![截图 2023-11-24 18-12-48](https://github.com/zjunlp/PromptKG/assets/71998483/a9205f79-21ae-453f-9ed5-2f2169d8e91e)

**Comment by CheaSim** [comment]
这个貌似是transformers版本的问题，麻烦您使用python3.8 并且transformers更新到4.6.0.
请先执行
```shell
pip install -r requirements.txt
```
再运行我们的脚本~

**Comment by zxlzr** [comment]
请问您的问题是否已解决？
