### ISSUE TITLE
bash ./scripts/kgrec/pretrain_item.sh  沒有ml20m dataset

### ISSUE THREAD

**Issue by JoeySmith1103** [zjunlp/PromptKG#48]
您好，在运行REC task的第一个script时，产生以下错误:
with open(f"./dataset/{self.args.dataset}/item2text.txt") as file:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/ml20m/item2text.txt'

请问有提供ml20m这个dataset吗?
谢谢!

**Comment by TimelordRi** [comment]
不好意思，我们忘记上传了这个数据集，请在下面的链接下载
[Google Drive](https://drive.google.com/drive/folders/1tEOuW7MdGcriuYp1pWOfwb-4oqT-FMzq?usp=drive_link) 或 [百度网盘](https://pan.baidu.com/s/188bs2q9Y_xDk3IgBopJuww?pwd=2icu)
