### ISSUE TITLE
RetrievalRE复现报错KeyError: -1

### ISSUE THREAD

**Issue by nanaseven7** [zjunlp/PromptKG#49]
您好，我在复现RetrievalRE时出现了一些问题。按照您提供的样例我成功实现了semeval的K=16、5，但在K=1下，运行bash scripts/knn_scripts/combine_knn_semeval.sh出现了如下报错：
  File "RetrievalRE/lit_models/transformer.py", line 372, in _eval
    if entity_logits[i][self.faissid2entityid[I[i][j]]] == 1000.:
KeyError: -1
请问您有遇到这种情况吗？该如何解决呢？

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们工作的关注，这里我们之前没遇到这种情况，可能是这里判断语句的边界超限了，您可以在line 372设置断点排查一下看看。

**Comment by nanaseven7** [comment]
好的哦，我试一下，感谢您的回复
