### ISSUE TITLE
PromptKGC project main.py has no reaction

### ISSUE THREAD

**Issue by pony-m** [zjunlp/PromptKG#5]
A lot of thanks for every replication!! Now the code starts to run, but it has no reaction after 3 downloads. As the attached image shows:
![error01](https://user-images.githubusercontent.com/84332561/173192816-5735fce0-3ae8-4c42-b9cc-c4b0c7976bb1.png)

**Comment by CheaSim** [comment]
Thank for your interest, we will fix in this week ( too much work to do now...)

**Comment by Aristomd** [comment]
您好，我的transformers版本是4.3.0但是还是ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'这个错误，我看报错信息是和pytorch_lightning有关是这个库的版本问题嘛？

**Comment by CheaSim** [comment]
> 您好，我的transformers版本是4.3.0但是还是ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'这个错误，我看报错信息是和pytorch_lightning有关是这个库的版本问题嘛？

应该是torchmetrics库版本的问题，推荐使用老一点的，我当时使用的是`pytorch_lightning==1.3.1`对应的`torchmetrics==0.5`。
