### ISSUE TITLE
你好，我有一些关于KGEditor的问题想请教一下

### ISSUE THREAD

**Issue by exxaid** [zjunlp/PromptKG#52]
1.在演示中，input为Jane Wyman|/people/person/places_lived./people/place_lived/location|[MASK]，Inductive Entity为Palm Springs，Origin Results为New York City United States of America United States Department of Housing and Urban Development，Add Results为Palm Springs Toy Story Emir Kusturica，增加了实体Palm Springs，输出为什么会多出来Toy Story和Emir Kusturica？
2.https://drive.google.com/drive/folders/1K1gag6eTCJ-x7WM-zbn6IRGX_B9fy4hD?usp=share_link和https://huggingface.co/datasets/zjunlp/KGEditor/tree/main/A-FB15k237这两个网址的数据集结构并不完全一样，我想要构建自己的数据集，应该参照哪一个呢？

**Comment by cheng-siyuan** [comment]
你好，感谢你对我们工作的关注！我在这里解答你的疑问。
1. 首先不好意思没有在demo中表明输出的含义，demo中演示的是KGE模型编辑前后输出的top 3实体预测列表，因为有些编辑后并不会修改正确，但是我们观察到可以极大概率提升被编辑实体的预测概率，所以在这里统一输出了top 3。
2. 数据集优先参考谷歌网盘的数据集。

**Comment by exxaid** [comment]
> 你好，感谢你对我们工作的关注！我在这里解答你的疑问。
> 
> 1. 首先不好意思没有在demo中表明输出的含义，demo中演示的是KGE模型编辑前后输出的top 3实体预测列表，因为有些编辑后并不会修改正确，但是我们观察到可以极大概率提升被编辑实体的预测概率，所以在这里统一输出了top 3。
> 2. 数据集优先参考谷歌网盘的数据集。

感谢您的回复，我还有一个问题，在运行结果中Eval/hits5，Eval/hits3，Eval/hits1，Eval/mean_rank，Eval/mrr，Eval/loc_hits1，Eval/loc_hits3， Eval/loc_hits5， Eval/loc_mean_rank，Eval/loc_mrr这些分别指什么呢

**Comment by cheng-siyuan** [comment]
> > 你好，感谢你对我们工作的关注！我在这里解答你的疑问。
> > 
> > 1. 首先不好意思没有在demo中表明输出的含义，demo中演示的是KGE模型编辑前后输出的top 3实体预测列表，因为有些编辑后并不会修改正确，但是我们观察到可以极大概率提升被编辑实体的预测概率，所以在这里统一输出了top 3。
> > 2. 数据集优先参考谷歌网盘的数据集。
> 
> 感谢您的回复，我还有一个问题，在运行结果中Eval/hits5，Eval/hits3，Eval/hits1，Eval/mean_rank，Eval/mrr，Eval/loc_hits1，Eval/loc_hits3， Eval/loc_hits5， Eval/loc_mean_rank，Eval/loc_mrr这些分别指什么呢

你好，这些指标分别对应于论文中的succ@k和RK@k。比如Eval/hits1对应的是succ@1，loc_hits3对应RK@3，mean_rank和loc_mean_rank用于计算ER_roc和RK_roc。计算方式在论文的Methodology章节中有详细说明。

**Comment by exxaid** [comment]
抱歉，请问一下Eval/mrr，Eval/loc_mrr是什么呢

**Comment by cheng-siyuan** [comment]
> 抱歉，请问一下Eval/mrr，Eval/loc_mrr是什么呢

抱歉，这个指标不应该出现在这里，和我们的实验metrics是没有关系的。这个MRR指标是KGC任务中的指标，全称是Mean Reciprocal Ranking，代表平均倒数排名，具体可以参考查询一些相关文章。

**Comment by exxaid** [comment]
> > 抱歉，请问一下Eval/mrr，Eval/loc_mrr是什么呢
> 
> 抱歉，这个指标不应该出现在这里，和我们的实验metrics是没有关系的。这个MRR指标是KGC任务中的指标，全称是Mean Reciprocal Ranking，代表平均倒数排名，具体可以参考查询一些相关文章。

好的，非常感谢
