### ISSUE TITLE
您好，关于KGEditor数据集的问题

### ISSUE THREAD

**Issue by exxaid** [zjunlp/PromptKG#53]
我按照WN18RR的add任务尝试构建了一个中文医学的数据集，但是运行之后的Eval/loc_hits特别低，应该是stable.jsonl的问题？在论文中提及的应该是用于评估局部性的模型原本预测正确的三元组，请问一下应该怎么构建呢？

**Comment by cheng-siyuan** [comment]
> 我按照WN18RR的add任务尝试构建了一个中文医学的数据集，但是运行之后的Eval/loc_hits特别低，应该是stable.jsonl的问题？在论文中提及的应该是用于评估局部性的模型原本预测正确的三元组，请问一下应该怎么构建呢？

你好，我们的处理方式是，在编辑之前过一遍整体的数据，选择之前预测正确的数据保留下来作为稳定性测试数据集。我们在论文图二中有做具体的说明。

**Comment by exxaid** [comment]
> > 我按照WN18RR的add任务尝试构建了一个中文医学的数据集，但是运行之后的Eval/loc_hits特别低，应该是stable.jsonl的问题？在论文中提及的应该是用于评估局部性的模型原本预测正确的三元组，请问一下应该怎么构建呢？
> 
> 你好，我们的处理方式是，在编辑之前过一遍整体的数据，选择之前预测正确的数据保留下来作为稳定性测试数据集。我们在论文图二中有做具体的说明。

好的，非常感谢
