### ISSUE TITLE
Installation error of LambdaKG

### ISSUE THREAD

**Issue by TangYiChing** [zjunlp/PromptKG#56]
Hello,

Could you advise me on resolving this error? 

> **ERROR: No matching distribution found for pytorch_lightning==1.6.3**

I followed the instructions and tried several workarounds but still had no luck.

```
conda create -n lambdakg python=3.8
conda activate lambdakg
cd PrompKG/lambdaKG
pip install -r requirements.txt
```

**Comment by TJ-coding** [comment]
I was able to fix the error by:
1. Downgrading the pip version to version 24.0: `pip install pip==24.0`
2. Changing the content of the requirements.txt to:
```
deepspeed==0.6.4
ipython==8.4.0
marisa_trie==0.7.7
numpy==1.20.3
pytorch_lightning==1.6.3
PyYAML==6.0
scikit_learn==1.1.2
torchmetrics==0.6.0
tqdm==4.62.3
transformers==4.6.0

torch==1.8.0
ujson==5.10.0
pandas==2.0.3
```
