### ISSUE TITLE
您好，关于KGEditor

### ISSUE THREAD

**Issue by bangiu** [zjunlp/PromptKG#59]
请问在论文中图二提到的用损坏数据集预训练模型以及之后筛选正确标记的数据的代码能否提供参考一下呢

**Comment by cheng-siyuan** [comment]
> 请问在论文中图二提到的用损坏数据集预训练模型以及之后筛选正确标记的数据的代码能否提供参考一下呢

你好，感谢你对我们工作的关注。很抱歉我们没有保存这部分筛选数据的代码，但是你只需要进行一次推理，将其中的错误数据和正确标记数据进行分离就好。

**Comment by bangiu** [comment]
> > 请问在论文中图二提到的用损坏数据集预训练模型以及之后筛选正确标记的数据的代码能否提供参考一下呢
> 
> 你好，感谢你对我们工作的关注。很抱歉我们没有保存这部分筛选数据的代码，但是你只需要进行一次推理，将其中的错误数据和正确标记数据进行分离就好。

请问预训练模型过程就是按照lambdaKG中的过程是吗

**Comment by zxlzr** [comment]
您好，KGEditor 训练是按https://github.com/zjunlp/PromptKG/tree/main/deltaKG 里的过程执行。 您还有其他问题吗？

**Comment by bangiu** [comment]
> 您好，KGEditor 训练是按https://github.com/zjunlp/PromptKG/tree/main/deltaKG 里的过程执行。 您还有其他问题吗？

您好，我指的是编辑前的模型权重预训练过程按照的哪一部分呢

**Comment by zxlzr** [comment]
您好，编辑前模型训练可以使用任意的开源代码来训，比如lambdakg或https://github.com/yao8839836/kg-bert

**Comment by zxlzr** [comment]
我们有开源训好的checkpoint，您可以直接用https://github.com/zjunlp/PromptKG/tree/main/deltaKG 里面有下载链接

**Comment by bangiu** [comment]
> 您好，编辑前模型训练可以使用任意的开源代码来训，比如lambdakg或https://github.com/yao8839836/kg-bert

好的，非常感谢
