### ISSUE TITLE
Optimal hyperparameters

### ISSUE THREAD

**Issue by ccchobits** [zjunlp/PromptKG#7]
Hi,

May I have the optimal hyperparameters used for the reported results in the original paper of GenKGC. We ran the script of `scripts/wn18rr.sh`, while this set of hyperparameters gives the following result:
![image](https://user-images.githubusercontent.com/31991851/179583023-e7656542-fa4a-4c9f-9403-4ebc112cabc4.png)
There is still a gap between this one and the reported results. Could you please check whether the given hyperparameters are for the reported result?

BTW, your work is quite interesting and we would like to reference your result in our current work. But as the MRR metric has not been reported in GenKGC original paper, we have to run this code to get the MRR result. If possible, please help us to check it. It is really appreciated.

**Comment by CheaSim** [comment]
Thank you for your interest.

Due to the entity type setting and demo prompt design, the results may be quite different. We will upload the new config file and `entity2text.txt` as soon as possible.

For `MRR metric`, as we use the auto-regresssive language models, we can easily get top50 predict entites but hard to get the ranks of true entity if it is not in the **top50**. I suggest you may ignore the `mrr` and `mr` metric in our settings.

**Comment by ccchobits** [comment]
Thank you for your reply. I understand with Beam Search evaluation approaches, it is hard to get the ranks of the target entities within the overall entity list.  But I still expect to have the config file. Hopefully, this request will not bring too much workload to you. Look forward to seeing your update. Thanks.

**Comment by CheaSim** [comment]
We reimplement a simper version of `GenKGC` in our toolkit repo, you can run the script below the get the result
```python
python main.py  \
   --max_epochs=30  --num_workers=8 \
   --model_name_or_path  facebook/bart-base \
   --num_sanity_val_steps 0 \
   --model_class BartKGC \
   --lit_model_class KGBartLitModel \
   --label_smoothing 0.1 \
   --data_class KGT5DataModule \
   --precision 16 \
   --batch_size 64 \
   --check_val_every_n_epoch 10 \
   --wandb \
   --use_ce_loss 1 \
   --dataset WN18RR \
   --eval_batch_size 24 \
   --max_seq_length 128 \
   --lr 1e-4 
```
And get the result in the picture, we reach higher `hits@1` and `hits@3`.
![1661581812271](https://user-images.githubusercontent.com/31753427/187018099-f912e8ba-b399-4603-b261-e690556d4ace.png)
