### ISSUE TITLE
没有 requirements.txt 文件

### ISSUE THREAD

**Issue by pony-m** [zjunlp/PromptKG#9]
您好，请问目前代码是能跑通的嘛？目前没有dependency文件，tutorial 也是空白的呀

**Comment by zxlzr** [comment]
您好tutorial 还在开发中，requirement.txt会马上上传抱歉

**Comment by pony-m** [comment]
哇……好的~期待

**Comment by zxlzr** [comment]
@pony-m  requirements.txt has been uploaded.
